name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      retain_days:
        description: retain days
        type: string
        default: "30"
        required: false
      keep_minimum_runs:
        description: minimum runs to keep
        type: string
        default: "6"
        required: false

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.retain_days }}
          keep_minimum_runs: ${{ inputs.keep_minimum_runs }}