# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Create MySQL image
      run: |
        cd mysql
        docker build -t bbsql .
        cd ..

    - name: Start MySQL container
      run: |
        docker run -p 3306:3306 --rm --name bbsql -d bbsql

    - name: Start Cassandra container
      run: |
        cd cassandra
        ./init_and_start_docker_container.sh 
        cd ..
      
      
    - name: Docker ps
      run: docker ps
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install deps
      run: pip3 install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - uses: actions/checkout@v2
    
    - name: Create MySQL image
      run: |
        cd mysql
        docker build -t bbsql .
        cd ..

    - name: Start MySQL container
      run: |
        docker run -p 3306:3306 --rm --name bbsql -d bbsql

    - name: Start Cassandra container
      run: |
        cd cassandra
        ./init_and_start_docker_container.sh 
        cd ..
      
      
    - name: Docker ps
      run: docker ps
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install deps
      run: pip3 install -r requirements.txt
      
    - name: Run test
      run: python3 ./test.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
    - run: echo ${{github.ref}} "deployed"
