name: Lint and Build

on:
  pull_request:
    branches:
      - main
      - develop # for testing
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - version.txt
jobs:
  lala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "pull request or develop"
        if: >- 
          github.event_name == 'pull_request' ||
          github.ref == 'ref/heads/develop'

      - run: echo "main and push and not ci"
        if: >- 
            github.ref == 'refs/heads/main' &&
            github.event_name == 'push' &&
            !startsWith(github.event.head_commit.message, 'ci')

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: >-
            ${{ 
            github.ref == 'refs/heads/main' &&
            github.event_name == 'push' &&
            !startsWith(github.event.head_commit.message, 'ci')
            }}
